services:
  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: jefialtes
      POSTGRES_PASSWORD: ghbkerb!@3
      POSTGRES_DB: exchangerates
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ghbkerb!@3

networks:
  app-network:
    driver: bridge